/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import Seguridad.Login;
import Seguridad.ManejoUsuarios;
import Seguridad.Usuario;
/**
 *
 * @author USUARIO
 */
public class RestaurarContraseña extends javax.swing.JFrame {
private menu menu;
private Login login;
private Usuario user;
    /**
     * Creates new form RestaurarContraseña
     */
    public RestaurarContraseña() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Imagen/cafe.png")).getImage());
        login = new Login();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordFieldContraseña = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombreUsuario2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombreUsuario1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        btnCerrar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurar Contraseña");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Contraseña Nueva");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jPasswordField1.setBackground(new java.awt.Color(255, 153, 102));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 200, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jPasswordFieldContraseña.setBackground(new java.awt.Color(255, 153, 102));
        getContentPane().add(jPasswordFieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 200, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre de Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, -1));

        jTextFieldNombreUsuario2.setBackground(new java.awt.Color(255, 153, 102));
        getContentPane().add(jTextFieldNombreUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 200, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre de Usuario (Admin)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 170, -1));

        jTextFieldNombreUsuario1.setBackground(new java.awt.Color(255, 153, 102));
        getContentPane().add(jTextFieldNombreUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 200, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Autenticacion.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 120, 130));

        jToggleButton1.setBackground(new java.awt.Color(255, 153, 102));
        jToggleButton1.setText("Restaurar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        btnCerrar.setBackground(new java.awt.Color(255, 153, 102));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Cerrar.png"))); // NOI18N
        btnCerrar.setToolTipText("<html>\n<head>\n\t<style>\n\t\t #contenido{ \n\t\tbackground: #003333;  /*Se le da un color de fondo*/\n\t\tcolor: white;\t\t  /*Color a la letra*/\n\t\t}\n\t</style>\n</head>\n<body>\n\t<div id=contenido>\n\t\t<h2>Cerrar Programa</h2>\n\t</div>\n</body>\n</html>");
        btnCerrar.setBorderPainted(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 30, 40));

        jLabelFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/blanco.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        int logeo = login.login(jTextFieldNombreUsuario1.getText(), jPasswordFieldContraseña.getText());//se hace el logeo
        switch (logeo) {// se verifica el valor obtenido 
            case 1:
                user = login.getUsuario(jTextFieldNombreUsuario1.getText());//se hace login enviando la informacion del admnistrador usuario logeado 
                ManejoUsuarios manejador = new ManejoUsuarios();
                int restaruar = manejador.ResestPass(jTextFieldNombreUsuario2.getText(), jPasswordField1.getText(), user.getUserId());// se restauta la contraseña
                switch (restaruar){
                    case -1:
                         JOptionPane.showMessageDialog(this, "Se necesita que un adminitrador restaure su clave","ERROR",JOptionPane.ERROR_MESSAGE);
                        break;
                    case 0:
                         JOptionPane.showMessageDialog(this, "El usuario que solicita restaurar contraseña no existe","ERROR",JOptionPane.ERROR_MESSAGE);
                        break;
                    case 1:
                         JOptionPane.showMessageDialog(this, "Se ha restaurado correctamente la constraseña","INFORMACION",JOptionPane.INFORMATION_MESSAGE);
                         this.dispose();
                         
                        break;
                    default:
                         JOptionPane.showMessageDialog(this, "ERROR Inesperado","ERROR",JOptionPane.ERROR_MESSAGE);
                        break;
                }
                break;
            case 0:
                JOptionPane.showMessageDialog(this, "Contraseña de Administrador incorrecta","ERROR",JOptionPane.ERROR_MESSAGE);//se informa que la contraseña es incorrecta
                break;
            case -1:
                JOptionPane.showMessageDialog(this, "Usuario Administradorincorrecto","ERROR",JOptionPane.ERROR_MESSAGE);//se informa que el usuario no existe
                break;
            default:
                JOptionPane.showMessageDialog(this, "Error Inesperado","ERROR",JOptionPane.ERROR_MESSAGE);//cualquier otro resultado
                break;
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordFieldContraseña;
    private javax.swing.JTextField jTextFieldNombreUsuario1;
    private javax.swing.JTextField jTextFieldNombreUsuario2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
