/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import Seguridad.Conexion;
import Seguridad.Usuario;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author USUARIO
 */
public class Visualizar_Ventas extends javax.swing.JFrame {
    private static Usuario user;
    /**
     * Creates new form Visualizar_Ventas
     */
   public Visualizar_Ventas(Usuario user) throws SQLException {
        this.user=user;//Se asigna el usuaario que hizo login
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Imagen/cafe.png")).getImage());
         
        initComponents();
        MostrarDatos("");
        try{
            Connection cn=Conexion.conectar();         
        
        this.setLocationRelativeTo(null);
        String sql = "SELECT ve.Total FROM venta ve";
        String sql2 = "SELECT dc.Subtotal from detallecompra dc";
       
        Statement st=cn.createStatement();
        ResultSet rs=st.executeQuery(sql);
        String dat[] = new String[3];
        while(rs.next()){
            dat[0]=rs.getString(1);
            jTextFieldTotalVentas.setText(dat[0]);
        }
        
        ResultSet rs2=st.executeQuery(sql2);
        String dat2[] = new String[3];
        while(rs2.next()){
            dat2[0]=rs2.getString(1);
            jTextFieldCompras.setText(dat2[0]);                 
        }
        
        int tv= Integer.parseInt( jTextFieldTotalVentas.getText() )  ;
        int tc= Integer.parseInt( jTextFieldCompras.getText() )  ;
        jTextFieldUtilidad.setText( Integer.toString(tv-tc) );
        jTextFieldUtilidadPorcentaje.setText( Integer.toString((tv-tc)*100/(tv)) +"%");
        }
        catch(SQLException ex){
          JOptionPane.showMessageDialog(null, "Error "+ex);
        }
    }
   
   
   private void MostrarDatos(String valor){
        try{Connection cn=Conexion.conectar();
            DefaultTableModel modelo=new DefaultTableModel(){
                @Override
                public boolean isCellEditable(int fil, int col) {
                    return col==7;
                }
            };
            modelo.addColumn("ID Cierre");
            modelo.addColumn("Total Cargo");
            modelo.addColumn("Total Venta");
            modelo.addColumn("Utilidad");
            modelo.addColumn("Fecha Cierre");
            
            jTable1.setModel(modelo);
            String sql="";
            
            if(valor.equals("")){
                sql="select * from Cierre";
            }else{
                sql="SELECT * FROM Cierre WHERE (idCierre='"+valor+"'  OR TotCargo='"+valor+"' OR TotVenta='"+valor+"')";
            }
            String []datos=new String [6];
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                modelo.addRow(datos);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error" +ex);
        }
    }
  /* void mostrardatoVent(String valor) {

        try {
            Connection cn = Conexion.conectar();

            DefaultTableModel modelo = new DefaultTableModel();

            modelo.addColumn("Producto");
            modelo.addColumn("Cantidad Vendida ");

            jTable1.setModel(modelo);
            String sql = "";

            if (valor.equals("")) {
                sql="Select inv.Nombre, m.Cantidad from menu m inner join inventario inv on m.Inventario_idInventario=inv.idInventario ";
            }

            String[] datos = new String[9];

            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);

                modelo.addRow(datos);

                jTable1.setModel(modelo);

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error" + ex);

        }
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMenu = new javax.swing.JButton();
        jTextFieldUtilidadPorcentaje = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldUtilidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCompras = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTotalVentas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMenu.setBackground(new java.awt.Color(255, 153, 102));
        jButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Login2.png"))); // NOI18N
        jButtonMenu.setBorderPainted(false);
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 40, 40));

        jTextFieldUtilidadPorcentaje.setBackground(new java.awt.Color(255, 153, 102));
        getContentPane().add(jTextFieldUtilidadPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 100, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("% Utilidad :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 100, -1));

        jTextFieldUtilidad.setBackground(new java.awt.Color(255, 153, 102));
        getContentPane().add(jTextFieldUtilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 100, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Utlidad :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 100, -1));

        jTextFieldCompras.setBackground(new java.awt.Color(255, 153, 102));
        jTextFieldCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldComprasActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 100, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Total Compras :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 100, -1));

        jTextFieldTotalVentas.setBackground(new java.awt.Color(255, 153, 102));
        getContentPane().add(jTextFieldTotalVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 100, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Total Ventas :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, -1));

        jTable1.setBackground(new java.awt.Color(255, 153, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 500, 280));

        jButton1.setBackground(new java.awt.Color(255, 153, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/check2.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        Fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/blanco.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        menu otro = new menu();
        this.setVisible(false);
        otro.setVisible(true);
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jTextFieldComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldComprasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {Connection cn=Conexion.conectar();
        {       java.util.Date d = new java.util.Date();
                java.sql.Date date = new java.sql.Date(d.getTime());
                PreparedStatement pst = cn.prepareStatement("INSERT INTO cierre(TotCargo,TotVenta,Utilidad,FechaCierre)Values(?,?,?,?)");
                pst.setString(1,jTextFieldTotalVentas.getText());
                pst.setString(2,jTextFieldCompras.getText());
                pst.setString(3,jTextFieldUtilidad.getText());
                pst.setDate(4,date);
                
                int a =pst.executeUpdate();
                if(a>0){
                    JOptionPane.showMessageDialog(null,"Registro Exitos");
                    MostrarDatos("");
                    jTextFieldTotalVentas.setText(null);
                    jTextFieldCompras.setText(null);
                    jTextFieldUtilidad.setText(null);
                }else{
                    JOptionPane.showMessageDialog(null,"Error al Agragar");
                }//fin del segundo if
        }//Fin del tray conexion 
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visualizar_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visualizar_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visualizar_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualizar_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                try {
                    new Visualizar_Ventas(user).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Visualizar_Ventas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCompras;
    private javax.swing.JTextField jTextFieldTotalVentas;
    private javax.swing.JTextField jTextFieldUtilidad;
    private javax.swing.JTextField jTextFieldUtilidadPorcentaje;
    // End of variables declaration//GEN-END:variables
}
